name: Test and Build (Single Platform)

on:
  workflow_dispatch:
    inputs:
      runner:
        description: 'Runner to build on'
        required: true
        type: choice
        options:
          - ubuntu-22.04
          - windows-2022
          - macos-12
      build_dr_version:
        description: 'DragonRuby version headers to build with'
        type: string
        default: '4.7'
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
      build_dr_version:
        type: string
        default: '4.7' # Minimum required version

env:
  TESTGAME_DIR: .github/workflows/testgame

jobs:
  build:
    runs-on: ${{ inputs.runner }}
    defaults:
      run:
        shell: bash
    outputs:
      dr_platform: ${{ steps.determine_dr_platform.outputs.dr_platform }}
    steps:
      - uses: actions/checkout@v3
      - name: Determine DragonRuby platform
        id: determine_dr_platform
        run: echo "dr_platform=$(scripts/dr_platform.sh)" >> "$GITHUB_OUTPUT"
      - name: Download dragonruby
        run: .github/workflows/download_dr_for_ci.sh ${{ inputs.build_dr_version }}
      - name: Windows build settings
        run: echo "MINGW_DIR=/C/ProgramData/chocolatey/lib/mingw/tools/install/mingw64" >> $GITHUB_ENV
        if: runner.os == 'Windows'
      - name: Build extension
        run: scripts/build.sh $TESTGAME_DIR/native/${{ steps.determine_dr_platform.outputs.dr_platform }}
      - uses: actions/upload-artifact@v3
        with:
          name: dragonruby-cext-libsocket-${{ steps.determine_dr_platform.outputs.dr_platform }}
          path: ${{ env.TESTGAME_DIR }}/native/${{ steps.determine_dr_platform.outputs.dr_platform }}/*
  test:
    needs:
      - build
    strategy:
      matrix:
        dr_version:
          - ${{ inputs.build_dr_version }}
          - '4.8' # Current DR version
      fail-fast: false
    runs-on: ${{ inputs.runner }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - name: Download dragonruby
        run: .github/workflows/download_dr_for_ci.sh ${{ matrix.dr_version }}
      - name: Download extension
        uses: actions/download-artifact@v3
        with:
          name: dragonruby-cext-libsocket-${{ needs.build.outputs.dr_platform }}
          path: ${{ env.TESTGAME_DIR }}/native/${{ needs.build.outputs.dr_platform }}
      - name: Run tests
        run: .github/workflows/run_tests.sh
